name: List Repository Content
on:
  push:
    branches:
      - main
      - master

jobs:
  listContent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Content
        run: |
          echo "### Repository Content" > README.md
          echo "" >> README.md

          for d in */; do
            echo "- \${d%/}" >> README.md
            cd \${d}
            for f in *; do
              echo "  - [\${f}](\${f})" >> ../README.md
            done
            cd ..
          done

      - name: Commit Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with repository content" || echo "No changes to commit"
          git push
